name: Github Actions Example

on: [push]

jobs:
   build:
      name: Building Project
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        
        - name: Build
           run: npm run build
