name: Github Actions Example

on: [push]

jobs:
   build:
      name: Building Project
      runs-on: ubuntu-latest

      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Build
           run: npm run build
