name: Deployment

on:
   push:
      branches: [master]

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2

         - name: Build Project
           run: npm run build

         - name: Deploy to GitHub
         - uses: JamesIves/github-pages-deploy-action@releases/v3
           with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              BRANCH: master
